# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'COVID5G' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for COVID5G
	pod 'SwiftLint'
	pod 'RxSwift'
	pod 'RxCocoa'
  pod 'Alamofire'
 	pod 'Moya/RxSwift', '~> 13.0'
	pod 'Gemini'
	pod 'ReachabilitySwift'
	end
